# Path to your oh-my-zsh installation.
export ZSH=$HOME/.zsh

autoload -Uz compinit && compinit

#load libs
source $ZSH/libs/git.zsh

# Load Theme
source $ZSH/themes/theme.zsh

# Load plugins
source $ZSH/plugins/git/git.plugin.zsh
source $ZSH/plugins/gitfast/gitfast.plugin.zsh

# Load Aliases
source $ZSH/aliases.zsh

# Load History Prefs
source $ZSH/history.zsh

# Load Complete Prefs
source $ZSH/completion.zsh

# Load User Prefs
source $ZSH/user.zsh
