set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()


" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" plugins
Plugin 'scrooloose/syntastic'

" markdown
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'



call vundle#end()            " required
filetype plugin indent on    " required
