set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()


" CUSTOM CONFIGS

" enable syntax highlighting
syntax enable


" enable all Python syntax highlighting features
let python_highlight_all = 1


" PLUGNS

" Vundle manage
Plugin 'gmarik/Vundle.vim'

" plugins
Plugin 'scrooloose/syntastic'

" themes
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()            " required


filetype plugin indent on    " required
set laststatus=2
" enable airline tab
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='papercolor'

" buffer navigation

nnoremap <Leader><LEFT> :bprevious<CR>
nnoremap <Leader><RIGHT> :bnext<CR>

